'use client';

import { useState, useEffect, useMemo } from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { Edit2, Info } from 'lucide-react';
import { getZIndexClass } from '@/lib/utils/z-index-utils';
import { formatMonthKey } from '@/lib/utils/date-utils';
import { buildLogMonthKey } from '@/data-store/keys';

/** Value for `<input type="datetime-local" />` from stored log timestamp (ISO or DD-MM-YYYY). */
function timestampToDatetimeLocal(v: string | undefined): string {
  if (!v) return '';
  const d = new Date(v);
  if (!isNaN(d.getTime())) {
    const pad = (n: number) => String(n).padStart(2, '0');
    return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`;
  }
  const m = String(v).match(/^(\d{2})-(\d{2})-(\d{4})/);
  if (m) {
    const d2 = new Date(Number(m[3]), Number(m[2]) - 1, Number(m[1]), 12, 0, 0, 0);
    if (!isNaN(d2.getTime())) {
      const pad = (n: number) => String(n).padStart(2, '0');
      return `${d2.getFullYear()}-${pad(d2.getMonth() + 1)}-${pad(d2.getDate())}T12:00`;
    }
  }
  return '';
}

interface LogEntryEditModalProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  entry: any;
  entityType: string;
  onSave: (updates: Record<string, any>, reason?: string) => Promise<void>;
  isSaving?: boolean;
}

// Immutable/computed fields that cannot be edited
const IMMUTABLE_FIELDS = [
  'id', 'entityId', 'event', 'editedAt', 'editedBy', 'lastUpdated', 
  'editHistory', 'isDeleted', 'deletedAt', 'deletedBy', 'deleteReason',
  // Computed fields (generated by processLogData)
  'displayName', 'currentStatus', 'formattedDate', 'formattedTime', 'displayDate',
  // Auto-generated log fields
  'changedAt', 'transition'
];

// Priority fields shown first
const PRIORITY_FIELDS = ['timestamp', 'name', 'description', 'taskType', 'status', 'priority', 'station'];

export function LogEntryEditModal({
  open,
  onOpenChange,
  entry,
  entityType,
  onSave,
  isSaving = false
}: LogEntryEditModalProps) {
  const [formData, setFormData] = useState<Record<string, any>>({});
  const [reason, setReason] = useState('');
  
  // Get editable fields from entry, intelligently sorted
  const editableFields = useMemo(() => {
    if (!entry) return [];
    
    return Object.keys(entry)
      .filter(key => !IMMUTABLE_FIELDS.includes(key))
      .sort((a, b) => {
        const aPriority = PRIORITY_FIELDS.indexOf(a);
        const bPriority = PRIORITY_FIELDS.indexOf(b);
        
        // Priority fields first
        if (aPriority !== -1 && bPriority !== -1) return aPriority - bPriority;
        if (aPriority !== -1) return -1;
        if (bPriority !== -1) return 1;
        
        // Then alphabetical
        return a.localeCompare(b);
      });
  }, [entry]);
  
  // Initialize form when entry changes
  useEffect(() => {
    if (entry) {
      const initialData: Record<string, any> = {};
      editableFields.forEach(field => {
        initialData[field] =
          field === 'timestamp'
            ? timestampToDatetimeLocal(entry.timestamp)
            : entry[field];
      });
      setFormData(initialData);
      setReason('');
    }
  }, [entry, editableFields]);

  // Check if there are any changes
  const hasChanges = () => {
    if (!entry) return false;
    
    for (const field of editableFields) {
      if (field === 'timestamp') {
        const cur = String(formData[field] ?? '').trim();
        const orig = timestampToDatetimeLocal(entry.timestamp);
        if (cur !== (orig || '')) return true;
        continue;
      }
      const currentValue = formData[field];
      const originalValue = entry[field];

      if (
        currentValue !== originalValue &&
        !(currentValue == null && originalValue == null)
      ) {
        return true;
      }
    }
    return false;
  };

  const handleFieldChange = (field: string, value: any) => {
    setFormData(prev => ({
      ...prev,
      [field]: value
    }));
  };

  const handleSave = async () => {
    if (!hasChanges()) {
      onOpenChange(false);
      return;
    }

    const updates: Record<string, any> = {};
    for (const field of editableFields) {
      if (field === 'timestamp') {
        const cur = String(formData[field] ?? '').trim();
        const orig = timestampToDatetimeLocal(entry.timestamp);
        if (cur !== (orig || '')) {
          if (!cur) return;
          const ms = new Date(cur).getTime();
          if (Number.isNaN(ms)) return;
          updates.timestamp = new Date(ms).toISOString();
        }
        continue;
      }
      const currentValue = formData[field];
      const originalValue = entry[field];

      if (currentValue !== originalValue) {
        updates[field] = currentValue;
      }
    }

    await onSave(updates, reason.trim() || undefined);
  };

  const timestampInvalid =
    editableFields.includes('timestamp') &&
    !(String(formData.timestamp ?? '').trim());

  // Smart field rendering with proper sizing
  const renderField = (field: string, value: any) => {
    if (field === 'timestamp') {
      return (
        <Input
          id={field}
          type="datetime-local"
          value={value != null ? String(value) : ''}
          onChange={(e) => handleFieldChange(field, e.target.value)}
          disabled={isSaving}
          className="font-mono text-sm"
        />
      );
    }

    const stringValue = value != null ? String(value) : '';
    const isLong = stringValue.length > 100;
    
    if (isLong) {
      return (
        <Textarea
          id={field}
          value={stringValue}
          onChange={(e) => handleFieldChange(field, e.target.value)}
          disabled={isSaving}
          rows={3}
          className="resize-none"
        />
      );
    }
    
    return (
      <Input
        id={field}
        value={stringValue}
        onChange={(e) => handleFieldChange(field, e.target.value)}
        disabled={isSaving}
      />
    );
  };

  // Format field labels
  const formatLabel = (field: string) => {
    // Convert camelCase/PascalCase to Title Case
    return field
      .replace(/([A-Z])/g, ' $1')
      .replace(/^./, str => str.toUpperCase())
      .trim();
  };

  if (!entry) return null;

  let kvLogListKey = '';
  try {
    const mmyy = formatMonthKey(entry.timestamp);
    kvLogListKey = buildLogMonthKey(entityType, mmyy);
  } catch {
    kvLogListKey = `(invalid timestamp — check logs:index:months:${entityType} for month keys)`;
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className={`max-w-4xl ${getZIndexClass('SUB_MODALS')}`}>
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Edit2 className="h-5 w-5 text-blue-600" />
            Edit Log Entry
          </DialogTitle>
        </DialogHeader>
        
        <div className="space-y-4">
          {/* KV / Upstash identifiers (log rows live in a LIST at this key; match element by id) */}
          <div className="space-y-2 p-3 rounded-lg border bg-muted/20 text-xs">
            <div className="font-semibold text-foreground flex items-center gap-1">
              <Info className="h-3.5 w-3.5 shrink-0" />
              Storage (manual edit in Upstash)
            </div>
            <div>
              <span className="text-muted-foreground block mb-0.5">Log entry id</span>
              <code className="block break-all rounded bg-muted px-2 py-1.5 text-[11px] leading-relaxed">
                {entry.id || '—'}
              </code>
            </div>
            <div>
              <span className="text-muted-foreground block mb-0.5">
                Redis list key (from entity + entry timestamp month)
              </span>
              <code className="block break-all rounded bg-muted px-2 py-1.5 text-[11px] leading-relaxed">
                {kvLogListKey}
              </code>
            </div>
            <p className="text-muted-foreground leading-snug">
              Value type is a <strong className="font-medium text-foreground">list</strong> of JSON strings. Find the element whose{' '}
              <code className="text-[10px]">id</code> matches above; if missing, try the same key for adjacent{' '}
              <code className="text-[10px]">MM-YY</code> months after a timestamp edit.
            </p>
          </div>

          {/* Compact metadata header */}
          <div className="flex flex-wrap items-center gap-x-4 gap-y-1 p-3 bg-muted/30 rounded-lg border border-dashed text-xs text-muted-foreground">
            <div className="flex items-center gap-1">
              <span className="font-medium">Event:</span> {entry.event || 'N/A'}
            </div>
            <span className="hidden sm:inline">•</span>
            <div>
              <span className="font-medium">Date:</span> {entry.timestamp || 'N/A'}
            </div>
            <span className="hidden sm:inline">•</span>
            <div className="min-w-0 break-all">
              <span className="font-medium">Entity id:</span> {entry.entityId || 'N/A'}
            </div>
          </div>

          {/* Two-column editable fields layout */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 max-h-[50vh] overflow-y-auto pr-2">
            {editableFields.map(field => {
              const value = formData[field];
              const isRequired = field === 'name';
              
              return (
                <div
                  key={field}
                  className={
                    field === 'description' || field === 'timestamp'
                      ? 'md:col-span-2'
                      : ''
                  }
                >
                  <Label 
                    htmlFor={field} 
                    className={`text-xs ${isRequired ? "after:content-['*'] after:ml-0.5 after:text-red-500" : ""}`}
                  >
                    {formatLabel(field)}
                  </Label>
                  {renderField(field, value)}
                  {field === 'timestamp' && String(value ?? '').trim() ? (
                    <p className="text-xs text-muted-foreground mt-1">
                      Log month after save:{' '}
                      {(() => {
                        const d = new Date(String(value));
                        return Number.isNaN(d.getTime())
                          ? '—'
                          : formatMonthKey(d);
                      })()}
                    </p>
                  ) : null}
                </div>
              );
            })}
          </div>

          {/* Reason for edit */}
          <div className="pt-2 border-t">
            <Label htmlFor="reason" className="text-xs">
              Reason for Edit <span className="text-muted-foreground">(Optional)</span>
            </Label>
            <Input
              id="reason"
              value={reason}
              onChange={(e) => setReason(e.target.value)}
              disabled={isSaving}
              placeholder="Why are you editing this entry?"
              className="mt-1"
            />
          </div>

          {/* No changes indicator */}
          {!hasChanges() && (
            <div className="flex items-center gap-2 p-2 bg-yellow-50 dark:bg-yellow-950/20 border border-yellow-200 dark:border-yellow-900 rounded-md text-xs text-yellow-800 dark:text-yellow-200">
              <Info className="h-3 w-3 flex-shrink-0" />
              <span>No changes detected</span>
            </div>
          )}
        </div>

        <DialogFooter className="gap-2">
          <Button variant="outline" onClick={() => onOpenChange(false)} disabled={isSaving}>
            Cancel
          </Button>
          <Button 
            onClick={handleSave}
            disabled={isSaving || !hasChanges() || timestampInvalid}
            className="bg-blue-600 hover:bg-blue-700"
          >
            {isSaving ? 'Saving...' : 'Save Changes'}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

