export const PREDEFINED_ACHIEVEMENTS = [
  "Financial Controller - Close month financials.",
  "Library Contributor - Create a research doc for the library.",
  "Content Creator - Create or fix an ebook or lesson in the library.",
  "Unit Master - Complete an entire unit (a lessons folder).",
  "System Blueprints - Draft a technical architecture diagram.",
  "Web3 Pioneer - Create an NFT collection, smart contract, or other web3 project.",
  "Game Designer - Design a gamified module or game.",
  "Master Plan - Draft a comprehensive 3-month project roadmap.",
  "Data Miner - Create a report finding patterns in raw data.",
  "Paradigm Shift - Propose a completely novel game mechanic or feature.",
  "Growth Embodiment - Demonstrate how you applied growth lessons in reality.",
  "Team Synergy - Coordinate a multi-person project milestone.",
  "The Pitch - Deliver a recorded pitch or presentation.",
  "Hype Train - Run a mock marketing campaign for a product.",
  "0 to 1 - Pitch and launch a new business system or micro-project.",
  "Bug Hunter - Find and fix an important bug in the digital universe.",
  "Interface Architect - Design a UI wireframe or mockup.",
  "The Craftsman - Create a craft or a physical prototype.",
  "The Closer - Successfully complete a mock negotiation or sale.",
  "First Canvas - Publish an original digital or physical artwork.",
  "The Mentor - Prepare and teach a class.",
  "Scrum Master - Successfully run a weekly sprint for a team.",
  "Master Marketer - Write a marketing plan."
];
